#!/bin/sh
# No diamond, Go for scripting is overkill !!!!!!!!!!!

# 1. %s: emoji name
# 2. %s: emoji but in Unicode
# 3. %s: emoji name
# 4. %s: image but in base64
css_fmt='img[alt=":%s:"],img[alt="%s"],li[aria-label^=":%s:"]>div{object-position:-9999px -9999px;content:var(--a);background-image:var(--a)!important;--a:url("data:image/png;base64,%s")}
'

# Fetch url
fetch() {
	for i in curl wget; do
		command -v "$i" >/dev/null && {
			fetch_cmd="$i"
			break
		}
	done

	[ -z "$fetch_cmd" ] && {
		echo install curl or wget kthx
		exit 1
	}

	case $fetch_cmd in
	wget) wget "$1" -O "$2" ;;
	curl) curl "$1" -o "$2" ;;
	esac
}


[ -f ./mapping.go ] || {
	fetch \
		'https://raw.githubusercontent.com/Bios-Marcel/discordemojimap/3fe443e1b82ead50ee62648e06630778e95fd0a1/mapping.go' \
		'./mapping.go'
}

[ -d ./blobmoji ] || {
	echo clone https://github.com/C1710/blobmoji/ kthx
	exit 1
}

echo 'img[class^="emoji"], li[id^="emoji"] > div {
	background-position: 0 !important;
	background-size: contain !important;
	background-repeat: no-repeat;
}'

while read -r l; do
	case $l in
	[!\"]*) continue ;;
	esac

	l="${l#*\"}"
	name="${l%%\"*}"
	unicode="${l#"${name}"\": \"}"
	unicode="${unicode%%\",}"
	cuni=

	case $unicode in
	\\[uU][[:alnum:]]*\\*)
		path="./blobmoji/png/128/emoji_u"

		u="$unicode"
		until [ -z "$u" ]; do
			case $u in
			\\U0*)
				u="${u##"${u%%[!\\U0]*}"}"
				f="${u%%\\*}"
			;;
			\\u*)
				u="${u##\\u}"
				f="${u%%\\*}"
			;;
			esac

			path="${path}${f}_"
			cuni="$cuni\\$f"
			u="${u##$f}"
		done

		path="${path%_}.png"
		;;
	\\u[[:alnum:]]*)
		path="./blobmoji/png/128/emoji_${unicode#\\}.png"
		cuni="\\${unicode##\\u}"
		;;
	\\U[[:alnum:]]*)
		path="./blobmoji/png/128/emoji_u${unicode##"${unicode%%[!\\U0]*}"}.png"
		cuni="\\${unicode##"${unicode%%[!\\U0]*}"}"
		;;
	esac

	[ -f "$path" ] || continue

	base64="$(base64 -w0 "$path")"
	base64="${base64%%
}"

	printf "$css_fmt" "$name" "$cuni" "$name" "$base64"
done <./mapping.go
